---
title: "Searching Fines"
author: "Caio Lente + Julio Trecenti"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(magrittr)
```

## Searcing Fines

```{r, eval = FALSE}
files <- carf::download_decision_year(2014, dir, min_page = 1, max_page = 50)
parsed <- carf::parse_decision(files)
decisions <- parsed$decicions
```

```{r, eval = FALSE}
decisions %>%
    dplyr::mutate(
      summary = stringr::str_to_upper(abjutils::rm_accent(summary)),
      restituicao = stringr::str_detect(summary, 'RESTITUICAO'),
      compensacao = stringr::str_detect(summary, 'COMPENSACAO'),
      auto_infracao = stringr::str_detect(summary, 'AUTO DE INFRACAO'),
      ressarcimento = stringr::str_detect(summary, 'RESSARCIMENTO'),
      num_types = restituicao + compensacao + auto_infracao + ressarcimento) %>%
  dplyr::filter(auto_infracao) %>%
  dplyr::select(id_lawsuit, summary)
```

## Studying Lawsuit IDs

```{r, eval = FALSE}
col_names <- c("place", "id", "year", "digit")

decisions %>%
  dplyr::select(id_lawsuit) %>%
  tidyr::separate(id_lawsuit, col_names, remove = FALSE) %>%
  dplyr::mutate_at(2:5, as.numeric) %>%
  dplyr::mutate(verif = (place + year + id) %% 97)
```
